extends Control
## TRAIT LOB — Level 3 (The Date), minigame round 1: HIDE IT.
##
## Every negative trait you accumulated in the apartment and the office becomes
## a piece of ammunition. You get exactly one shot with each. Stick it into the
## socket set into the far top-right corner and that trait is OBSCURED — the
## date never finds out. Miss and it drops to the floor, where it lies in plain
## sight for the rest of the evening.
##
## The throw is a Worms grenade — pick the angle, hold to charge, release — but
## the target is a small square socket flush in the corner, so the shot that
## solves it is flat and fast. You are sticking an arrow into a mark, not
## lobbing something into a bucket. There is no full trajectory solution on
## screen: an arrow for power, the first fifth of the arc, and your judgement.
##
## The socket takes as many traits as you can land in it — hit it every time
## and you walk in with nothing showing.
##
## Anxiety is inherited from the previous levels and is the entire difficulty
## curve. It applies a vertical wobble to your aim in four steps, one per 25
## points, and it winds the charge meter up faster than you can read it.
##
## Public API:
##   show_and_play(traits: Array, anxiety: int) -> Dictionary
##     traits: entries shaped exactly like AnxietySystem.listing():
##             {id, label, amount, tex, tip, locked}
##     returns { outcome, obscured, exposed, shots, anxiety }
##       outcome  : "done" | "cancel" | "empty"
##       obscured : [trait_id, …]  stuck in the socket
##       exposed  : [trait_id, …]  on the floor, eligible for the reveal
##       shots    : [{id, result, angle, power}, …] per-shot log
##
## Round 2 (the reveal — RNG picks from `exposed`) is deliberately NOT here.
## This script's only job is producing a clean obscured/exposed split.
##
## Art: trait_lob_minigame/*.png, regenerated by _src_magenta/gen_art.py.
## The board geometry constants below MUST match that script exactly.

signal minigame_finished(result: Dictionary)

# ------------------------------------------------------------------ art ------
const ART_DIR := "res://trait_lob_minigame/"
const BACKDROP_PNG := ART_DIR + "tl_backdrop.png"
const SOCKET_PNG := ART_DIR + "tl_socket.png"
const DOT_PNG := ART_DIR + "tl_dot.png"
const PUFF_PNG := ART_DIR + "tl_puff.png"

## The thrower is the real Player 2 sprite, not a bespoke one — 4x4 sheet,
## frame 8 is the right-facing idle (see the direction table in player_body.gd).
const PLAYER_SHEET := "res://julian assange sprite sheet black.png"
const PLAYER_SHEET_FALLBACK := "res://julian assange sprite sheet.png"
const PLAYER_FRAME_RIGHT := 8
const PLAYER_SHEET_COLS := 4
const PLAYER_SHEET_ROWS := 4
const PLAYER_ZOOM := 2          ## integer only, or the pixels go soft

## Board-space geometry — MUST match gen_art.py exactly.
## A long, low room: 548x256 is nearly 2.2:1, drawn at 2x for a 1096x512 stage.
const BOARD_W := 548
const BOARD_H := 256
## The ceiling is SOLID. Overcook a high lob and it clatters off the beams.
const CEILING_Y := 14.0
const FLOOR_Y := 208.0
const LAUNCH_X := 54.0
const LAUNCH_Y := 176.0
const STAND_X := 50.0

## ONE square socket. Interior is exactly one icon square, so a clean hit fills
## it perfectly. It RELOCATES before every throw, which is the real difficulty:
## you cannot groove one shot and repeat it, you have to re-read the range each
## time and the anxiety wobble is fighting you while you do.
const SOCKET_OUTER := 15.0
const SOCKET_MOVES := true
## Where it is allowed to appear — the upper right of the room. Every position
## in here was checked reachable: best angles land between 19 and 25 degrees and
## the power window never drops below 0.65 of the meter. The bottom edge stops
## short of the mirror so the socket never sits on top of it.
const SOCKET_ROAM_X0 := 396.0
const SOCKET_ROAM_X1 := 528.0
const SOCKET_ROAM_Y0 := 18.0
const SOCKET_ROAM_Y1 := 66.0
## Never re-roll onto (nearly) the same spot — a "move" you cannot see is worse
## than not moving at all.
const SOCKET_MIN_MOVE := 34.0
## Where it starts, and where it stays if SOCKET_MOVES is off.
const SOCKET_HOME_X := 526.0
const SOCKET_HOME_Y := 20.0

## "Mostly fits and it connects": capture when the icon centre lands within
## this many board units of the socket centre, on either axis. 13 is generous
## on purpose — the icon is 13 wide and the socket 15, so this is roughly "any
## real contact counts". THIS IS THE DIFFICULTY KNOB. Tightening it toward 8
## makes the corner brutal at high anxiety; loosening it past 14 makes the
## throw forgiving enough that anxiety stops mattering.
const CAPTURE_HALF := 13.0

const SOCKET_CELL_W := 15
const SOCKET_CELL_H := 17
const DOT_CELL := 5
const PUFF_CELL := 26

const SCALE := 2.0            ## integer upscale so pixels stay crisp

## Ammo is drawn EXACTLY the way the anxiety bar draws it, chrome included:
## anxiety_bar.gd uses a ROW_ICON_PX (26) bordered square slot with the icon
## itself at ROW_ICON_PX - 6 inside it. Reusing the whole slot — not just the
## texture — is what makes every trait a uniform square, whatever shape the
## source art happens to be.
const SLOT_PX := 26          ## == anxiety_bar.gd ROW_ICON_PX
const ICON_PX := SLOT_PX - 6 ## == the TextureRect size inside that slot

# --------------------------------------------------------------- palette -----
const C_INK := Color("#1B1020")
const C_PLATE := Color("#42204A")
const C_MAROON := Color("#8C2E48")
const C_RUST := Color("#C87A55")
const C_RED := Color("#E36956")
const C_ORANGE := Color("#EFA660")
const C_ORANGE_LT := Color("#FFD07A")
const C_CREAM := Color("#FFFFEB")
const C_GOLD := Color("#FFE478")
const C_GREEN := Color("#3CA370")
const C_GREY := Color("#6E6A80")
const C_GREY_LT := Color("#C6C3D6")

# ------------------------------------------------------------- tuning --------
## Board units per second squared. Solved against the geometry above, not
## guessed. The speed range is deliberately NARROW — it brackets the two real
## solutions rather than spanning everything physically possible. That is the
## single biggest lever on fairness here: a wide range means one notch of the
## power meter is worth a huge jump in distance, and with holders this small
## the shot stops being readable. Bracketing it buys the precision back.
##
## Gravity, the bounce constants, the wobble tiers and the charge rates are all
## unchanged from the previous build — the throw feels identical. Only the
## speed bracket moved, and it had to: the socket is now ~480 units away in the
## far corner instead of ~250, which is simply out of range at the old speeds.
##
## The solution that falls out is flat and quick: ~23 degrees at roughly 29-66%
## power. Full power overshoots into the wall.
const GRAVITY := 500.0
const SPEED_MIN := 855.0
const SPEED_MAX := 1475.0
const ANGLE_MIN := 8.0
const ANGLE_MAX := 80.0
## Right on the corner socket's solution.
const ANGLE_START := 23.0

## Worst trait first: your biggest problem is the shot you take while the meter
## still feels unfamiliar.
const AMMO_ORDER_WORST_FIRST := true

## --- anxiety --------------------------------------------------------------
## Vertical aim wobble, in 25-point steps: 0-24, 25-49, 50-74, 75-99, 100.
## This is the headline difficulty knob and it is deliberately VISIBLE — the
## arrow drifts up and down in front of you and you throw into the gap.
## Degrees of amplitude per tier.
const WOBBLE_TIER_DEG := [0.0, 2.0, 4.0, 6.5, 9.5]
## Wobble speed also climbs, so high anxiety is fast AND wide.
const WOBBLE_TIER_HZ := [0.0, 0.85, 1.15, 1.45, 1.8]

## Aim nudge speed, calm -> maxed. Faster is worse: you overshoot the angle.
const AIM_SPEED := [30.0, 52.0]
## Charge meter travel, full sweeps 0->1 per second. Calm is a slow ~2.9s round
## trip you can place precisely; maxed out is 0.55s and basically a reflex test.
const CHARGE_RATE := [0.35, 1.80]
## Small residual error on launch speed. The wobble does the heavy lifting now.
const RELEASE_SPEED_ERR := [0.0, 0.06]

## Only the opening fifth of the arc is drawn. Enough to read the angle, not
## enough to solve the shot.
const TRACE_FRACTION := 0.20
const TRACE_DOTS := 6

## Strength arrow, board units.
const ARROW_MIN_LEN := 16.0
const ARROW_MAX_LEN := 74.0
const ARROW_SHAFT_HW := 2.5    ## half-width
const ARROW_HEAD_LEN := 13.0
const ARROW_HEAD_HW := 7.5

## Bounce response, 0..1 energy kept. A bounce off ANYTHING disqualifies the
## shot — the corner is not a backboard, and without this rule the right wall
## rebounds everything straight into the socket.
const BOUNCE_FLOOR := 0.42
const BOUNCE_WALL := 0.45
const BOUNCE_CEILING := 0.45
const FRICTION := 0.72
const SETTLE_SPEED := 30.0

const FLIGHT_STEP := 1.0 / 240.0
const FLIGHT_MAX_SEC := 9.0
const INPUT_GATE_FRAMES := 12

enum Phase { AIM, CHARGE, FLIGHT, SETTLE }

# ----------------------------------------------------------------- state -----
var _built := false
var _pixel_font: Font

var _tex_backdrop: Texture2D
var _tex_socket: Texture2D
var _tex_dot: Texture2D
var _tex_puff: Texture2D
var _tex_player: Texture2D

var _dim: ColorRect
var _outer: PanelContainer
var _title_label: Label
var _anx_label: Label
var _stage: Control
var _player_rect: TextureRect
var _socket_rect: TextureRect
var _socket_count_label: Label
## Top-left corner of the socket in board space. Moves every throw.
var _socket_pos := Vector2(SOCKET_HOME_X, SOCKET_HOME_Y)
var _projectile: PanelContainer
var _puff_rect: TextureRect
var _dots: Array = []
var _floor_icons: Array = []       ## missed traits left lying on the ground
var _arrow_edge: Polygon2D
var _arrow_fill: Polygon2D
var _queue_row: HBoxContainer
var _card_slot: PanelContainer
var _card_icon: TextureRect
var _card_name: Label
var _card_amount: Label
var _shots_label: Label
var _power_label: Label
var _hint_label: Label
var _call_label: Label
var _flash: ColorRect
var _summary: PanelContainer
var _summary_rows: VBoxContainer

var _traits: Array = []
var _anxiety := 25
var _diff := 0.0
var _tier := 1
var _index := 0
var _phase: int = Phase.AIM
var _angle := ANGLE_START
var _charge := 0.0
var _charge_dir := 1.0
var _wobble_t := 0.0
var _socket_count := 0
var _obscured: Array = []
var _exposed: Array = []
var _shots: Array = []
var _running := false
var _abort_requested := false
var _input_gate_frame := 0


func _ready() -> void:
	set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)
	mouse_filter = Control.MOUSE_FILTER_STOP
	process_mode = Node.PROCESS_MODE_ALWAYS
	visible = false
	if ResourceLoader.exists("res://PressStart2P-Regular.ttf"):
		_pixel_font = load("res://PressStart2P-Regular.ttf")
	_load_art()
	_build_ui()


# ------------------------------------------------------------------ helpers --
func _load_tex(path: String) -> Texture2D:
	if path.is_empty():
		return null
	if ResourceLoader.exists(path):
		var t := load(path) as Texture2D
		if t != null:
			return t
	var img := Image.new()
	if img.load(path) == OK:
		return ImageTexture.create_from_image(img)
	push_warning("[TraitLob] missing art: %s" % path)
	return null


func _load_art() -> void:
	_tex_backdrop = _load_tex(BACKDROP_PNG)
	_tex_socket = _load_tex(SOCKET_PNG)
	_tex_dot = _load_tex(DOT_PNG)
	_tex_puff = _load_tex(PUFF_PNG)
	_tex_player = _load_tex(PLAYER_SHEET)
	if _tex_player == null:
		_tex_player = _load_tex(PLAYER_SHEET_FALLBACK)


func _atlas(tex: Texture2D, index: int, cell_w: int, cell_h: int) -> Texture2D:
	if tex == null:
		return null
	var a := AtlasTexture.new()
	a.atlas = tex
	a.region = Rect2(index * cell_w, 0, cell_w, cell_h)
	a.filter_clip = true
	return a


## Grid atlas, for the 4x4 player walk sheet.
func _atlas_grid(tex: Texture2D, frame: int, cols: int, rows: int) -> Texture2D:
	if tex == null:
		return null
	var cw: int = int(tex.get_width() / float(cols))
	var ch: int = int(tex.get_height() / float(rows))
	var a := AtlasTexture.new()
	a.atlas = tex
	a.region = Rect2((frame % cols) * cw, (frame / cols) * ch, cw, ch)
	a.filter_clip = true
	return a


func _pixel_rect(tex: Texture2D, w: float, h: float) -> TextureRect:
	var r := TextureRect.new()
	r.texture = tex
	r.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
	r.stretch_mode = TextureRect.STRETCH_SCALE
	r.expand_mode = TextureRect.EXPAND_IGNORE_SIZE
	r.mouse_filter = Control.MOUSE_FILTER_IGNORE
	r.custom_minimum_size = Vector2(w, h)
	r.size = Vector2(w, h)
	return r


func _style_label(lab: Label, size: int, color: Color) -> void:
	if _pixel_font:
		lab.add_theme_font_override("font", _pixel_font)
	lab.add_theme_font_size_override("font_size", size)
	lab.add_theme_color_override("font_color", color)
	lab.mouse_filter = Control.MOUSE_FILTER_IGNORE


func _panel_style(bg: Color, border: Color, width: int = 2, radius: int = 4,
		margin: int = 8) -> StyleBoxFlat:
	var st := StyleBoxFlat.new()
	st.bg_color = bg
	st.border_color = border
	st.set_border_width_all(width)
	st.set_corner_radius_all(radius)
	st.set_content_margin_all(margin)
	return st


## Board coordinates -> stage pixels.
func _px(v: float) -> float:
	return v * SCALE


func _pxv(v: Vector2) -> Vector2:
	return v * SCALE


func _place(node: Control, board_x: float, board_y: float) -> void:
	node.position = Vector2(_px(board_x), _px(board_y))


func _scaled(pair: Array) -> float:
	return lerpf(float(pair[0]), float(pair[1]), _diff)


func _socket_centre() -> Vector2:
	return _socket_pos + Vector2(SOCKET_OUTER, SOCKET_OUTER) * 0.5


## Checked only while the shot is still clean — a carom does not count as
## sticking it.
func _capture_hit(p: Vector2) -> bool:
	var c: Vector2 = _socket_centre()
	return absf(p.x - c.x) <= CAPTURE_HALF and absf(p.y - c.y) <= CAPTURE_HALF


## Drop the socket somewhere new in the roam box, far enough from where it was
## that the move actually reads.
func _relocate_socket() -> void:
	if not SOCKET_MOVES:
		return
	var prev: Vector2 = _socket_pos
	var next: Vector2 = prev
	for _attempt in range(24):
		next = Vector2(
			randf_range(SOCKET_ROAM_X0, SOCKET_ROAM_X1),
			randf_range(SOCKET_ROAM_Y0, SOCKET_ROAM_Y1))
		if next.distance_to(prev) >= SOCKET_MIN_MOVE:
			break
	_socket_pos = next
	if _socket_rect:
		_place(_socket_rect, _socket_pos.x, _socket_pos.y)


## The uniform ammo square. This is anxiety_bar.gd's hover-row slot rebuilt
## exactly: same 26px bordered panel, same 20px icon centred inside it, same
## red/green border rule. Reusing the chrome and not just the texture is what
## makes every trait the same shape no matter what the source art looks like.
func _make_icon_square(tex: Texture2D, amount: int, locked: bool,
		border_override = null) -> PanelContainer:
	var slot := PanelContainer.new()
	slot.custom_minimum_size = Vector2(SLOT_PX, SLOT_PX)
	slot.size = Vector2(SLOT_PX, SLOT_PX)
	slot.mouse_filter = Control.MOUSE_FILTER_IGNORE
	var border: Color = C_GREEN if amount < 0 else C_RED
	if locked:
		border = Color(0.62, 0.10, 0.10, 1.0)
	if border_override != null:
		border = border_override
	var st := StyleBoxFlat.new()
	st.bg_color = Color(0.10, 0.07, 0.06, 0.96)
	st.border_color = border
	st.set_border_width_all(2)
	st.set_corner_radius_all(2)
	st.set_content_margin_all(2)
	slot.add_theme_stylebox_override("panel", st)

	# Always built, even with a null texture, so the card can swap it per shot.
	var ic := TextureRect.new()
	ic.name = "Icon"
	ic.texture = tex
	ic.expand_mode = TextureRect.EXPAND_IGNORE_SIZE
	ic.stretch_mode = TextureRect.STRETCH_KEEP_ASPECT_CENTERED
	ic.custom_minimum_size = Vector2(ICON_PX, ICON_PX)
	ic.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
	ic.mouse_filter = Control.MOUSE_FILTER_IGNORE
	slot.add_child(ic)
	return slot


# ----------------------------------------------------------------- build -----
func _build_ui() -> void:
	if _built:
		return
	_built = true

	_dim = ColorRect.new()
	_dim.color = Color(0.02, 0.01, 0.04, 0.86)
	_dim.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)
	_dim.mouse_filter = Control.MOUSE_FILTER_STOP
	add_child(_dim)

	var center := CenterContainer.new()
	center.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)
	center.mouse_filter = Control.MOUSE_FILTER_IGNORE
	add_child(center)

	_outer = PanelContainer.new()
	_outer.add_theme_stylebox_override("panel",
		_panel_style(C_PLATE, C_INK, 3, 8, 6))
	_outer.mouse_filter = Control.MOUSE_FILTER_IGNORE
	center.add_child(_outer)

	var col := VBoxContainer.new()
	col.add_theme_constant_override("separation", 5)
	col.mouse_filter = Control.MOUSE_FILTER_IGNORE
	_outer.add_child(col)

	col.add_child(_build_header())
	col.add_child(_build_stage())

	_build_summary()


func _build_header() -> Control:
	var bar := PanelContainer.new()
	bar.add_theme_stylebox_override("panel",
		_panel_style(Color(0.06, 0.04, 0.08, 0.95), C_GOLD, 2, 4, 6))
	bar.mouse_filter = Control.MOUSE_FILTER_IGNORE

	var row := HBoxContainer.new()
	row.add_theme_constant_override("separation", 12)
	row.mouse_filter = Control.MOUSE_FILTER_IGNORE
	bar.add_child(row)

	_title_label = Label.new()
	_title_label.text = "THE DATE  —  ROUND 1:  HIDE IT"
	_style_label(_title_label, 12, C_GOLD)
	_title_label.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	row.add_child(_title_label)

	_socket_count_label = Label.new()
	_socket_count_label.text = ""
	_style_label(_socket_count_label, 10, C_GREEN)
	_socket_count_label.horizontal_alignment = HORIZONTAL_ALIGNMENT_RIGHT
	row.add_child(_socket_count_label)

	_anx_label = Label.new()
	_anx_label.text = "ANXIETY 25"
	_style_label(_anx_label, 10, C_RED)
	_anx_label.horizontal_alignment = HORIZONTAL_ALIGNMENT_RIGHT
	row.add_child(_anx_label)

	return bar


func _build_stage() -> Control:
	var frame := PanelContainer.new()
	frame.add_theme_stylebox_override("panel",
		_panel_style(C_INK, C_MAROON, 2, 4, 2))
	frame.mouse_filter = Control.MOUSE_FILTER_IGNORE

	_stage = Control.new()
	_stage.custom_minimum_size = Vector2(_px(BOARD_W), _px(BOARD_H))
	_stage.clip_contents = true
	_stage.mouse_filter = Control.MOUSE_FILTER_IGNORE
	frame.add_child(_stage)

	_stage.add_child(_pixel_rect(_tex_backdrop, _px(BOARD_W), _px(BOARD_H)))

	# --- the socket -------------------------------------------------------
	_socket_rect = _pixel_rect(_atlas(_tex_socket, 0, SOCKET_CELL_W, SOCKET_CELL_H),
		_px(SOCKET_CELL_W), _px(SOCKET_CELL_H))
	_place(_socket_rect, _socket_pos.x, _socket_pos.y)
	_stage.add_child(_socket_rect)

	# --- the thrower: real Player 2 sprite, right-facing idle --------------
	var pw := 0.0
	var ph := 0.0
	if _tex_player != null:
		pw = (_tex_player.get_width() / float(PLAYER_SHEET_COLS)) * float(PLAYER_ZOOM)
		ph = (_tex_player.get_height() / float(PLAYER_SHEET_ROWS)) * float(PLAYER_ZOOM)
	_player_rect = _pixel_rect(
		_atlas_grid(_tex_player, PLAYER_FRAME_RIGHT, PLAYER_SHEET_COLS, PLAYER_SHEET_ROWS),
		pw, ph)
	_player_rect.position = Vector2(_px(STAND_X) - pw * 0.5, _px(FLOOR_Y + 2.0) - ph)
	_stage.add_child(_player_rect)

	# --- trajectory trace (short) -----------------------------------------
	for i in range(TRACE_DOTS):
		var d := _pixel_rect(_atlas(_tex_dot, 0, DOT_CELL, DOT_CELL),
			_px(DOT_CELL), _px(DOT_CELL))
		d.visible = false
		_stage.add_child(d)
		_dots.append(d)

	# --- strength arrow (Node2D, so it can be an actual arrow) -------------
	_arrow_edge = Polygon2D.new()
	_arrow_edge.color = C_INK
	_stage.add_child(_arrow_edge)
	_arrow_fill = Polygon2D.new()
	_arrow_fill.color = C_GOLD
	_stage.add_child(_arrow_fill)
	_set_arrow_visible(false)

	# --- the trait in flight ----------------------------------------------
	# The thing in flight is the same square the anxiety bar shows, not a bare
	# texture — so what you throw looks like what you saw on the bar.
	_projectile = _make_icon_square(null, 1, false)
	_projectile.pivot_offset = Vector2(SLOT_PX, SLOT_PX) * 0.5
	_projectile.visible = false
	_stage.add_child(_projectile)

	_puff_rect = _pixel_rect(_atlas(_tex_puff, 0, PUFF_CELL, PUFF_CELL),
		_px(PUFF_CELL), _px(PUFF_CELL))
	_puff_rect.visible = false
	_stage.add_child(_puff_rect)

	_build_queue_overlay()
	_build_card_overlay()
	_build_hint_overlay()
	_build_call_overlay()

	_flash = ColorRect.new()
	_flash.color = Color(1, 1, 1, 0)
	_flash.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)
	_flash.mouse_filter = Control.MOUSE_FILTER_IGNORE
	_stage.add_child(_flash)

	return frame


func _build_queue_overlay() -> void:
	var holder := PanelContainer.new()
	holder.add_theme_stylebox_override("panel",
		_panel_style(Color(0.04, 0.02, 0.05, 0.82), C_MAROON, 2, 3, 5))
	holder.mouse_filter = Control.MOUSE_FILTER_IGNORE
	holder.position = Vector2(10.0, 8.0)
	holder.custom_minimum_size = Vector2(300, 0)
	_stage.add_child(holder)

	var vb := VBoxContainer.new()
	vb.add_theme_constant_override("separation", 3)
	vb.mouse_filter = Control.MOUSE_FILTER_IGNORE
	holder.add_child(vb)

	var head := HBoxContainer.new()
	head.add_theme_constant_override("separation", 10)
	head.mouse_filter = Control.MOUSE_FILTER_IGNORE
	vb.add_child(head)

	var lab := Label.new()
	lab.text = "AMMO"
	_style_label(lab, 8, C_ORANGE_LT)
	lab.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	head.add_child(lab)

	_shots_label = Label.new()
	_shots_label.text = "0 / 0"
	_style_label(_shots_label, 8, C_GREY_LT)
	_shots_label.horizontal_alignment = HORIZONTAL_ALIGNMENT_RIGHT
	head.add_child(_shots_label)

	_queue_row = HBoxContainer.new()
	_queue_row.add_theme_constant_override("separation", 4)
	_queue_row.mouse_filter = Control.MOUSE_FILTER_IGNORE
	vb.add_child(_queue_row)


func _build_card_overlay() -> void:
	var card := PanelContainer.new()
	card.add_theme_stylebox_override("panel",
		_panel_style(Color(0.04, 0.02, 0.05, 0.88), C_RED, 2, 3, 6))
	card.mouse_filter = Control.MOUSE_FILTER_IGNORE
	card.position = Vector2(10.0, _px(BOARD_H) - 100.0)
	_stage.add_child(card)

	var row := HBoxContainer.new()
	row.add_theme_constant_override("separation", 8)
	row.mouse_filter = Control.MOUSE_FILTER_IGNORE
	card.add_child(row)

	_card_slot = _make_icon_square(null, 1, false)
	row.add_child(_card_slot)
	_card_icon = _card_slot.get_node("Icon") as TextureRect

	var text_col := VBoxContainer.new()
	text_col.add_theme_constant_override("separation", 4)
	text_col.mouse_filter = Control.MOUSE_FILTER_IGNORE
	text_col.size_flags_vertical = Control.SIZE_SHRINK_CENTER
	row.add_child(text_col)

	_card_name = Label.new()
	_card_name.text = ""
	_card_name.custom_minimum_size = Vector2(150, 0)
	_card_name.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART
	_style_label(_card_name, 9, C_CREAM)
	text_col.add_child(_card_name)

	_card_amount = Label.new()
	_card_amount.text = ""
	_style_label(_card_amount, 10, C_RED)
	text_col.add_child(_card_amount)

	_power_label = Label.new()
	_power_label.text = ""
	_style_label(_power_label, 9, C_GOLD)
	text_col.add_child(_power_label)


func _build_hint_overlay() -> void:
	_hint_label = Label.new()
	_hint_label.text = ""
	_style_label(_hint_label, 8, C_GREY_LT)
	_hint_label.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	_hint_label.custom_minimum_size = Vector2(_px(BOARD_W), 0)
	_hint_label.size = Vector2(_px(BOARD_W), 16)
	_hint_label.position = Vector2(0.0, _px(BOARD_H) - 26.0)
	_stage.add_child(_hint_label)


func _build_call_overlay() -> void:
	_call_label = Label.new()
	_call_label.text = ""
	_style_label(_call_label, 22, C_CREAM)
	_call_label.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	_call_label.position = Vector2(0.0, _px(BOARD_H) * 0.30)
	_call_label.custom_minimum_size = Vector2(_px(BOARD_W), 0)
	_call_label.size = Vector2(_px(BOARD_W), 30)
	_stage.add_child(_call_label)


func _build_summary() -> void:
	var holder := CenterContainer.new()
	holder.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)
	holder.mouse_filter = Control.MOUSE_FILTER_IGNORE
	add_child(holder)

	_summary = PanelContainer.new()
	_summary.add_theme_stylebox_override("panel",
		_panel_style(Color(0.04, 0.02, 0.05, 0.97), C_GOLD, 3, 6, 14))
	_summary.mouse_filter = Control.MOUSE_FILTER_IGNORE
	_summary.visible = false
	holder.add_child(_summary)

	_summary_rows = VBoxContainer.new()
	_summary_rows.add_theme_constant_override("separation", 6)
	_summary_rows.mouse_filter = Control.MOUSE_FILTER_IGNORE
	_summary.add_child(_summary_rows)


# ------------------------------------------------------------ public API -----
func show_and_play(traits: Array, anxiety: int) -> Dictionary:
	if not _built:
		_load_art()
		_build_ui()

	_anxiety = clampi(anxiety, 0, 100)
	_diff = clampf(float(_anxiety) / 100.0, 0.0, 1.0)
	_tier = clampi(int(_anxiety / 25), 0, WOBBLE_TIER_DEG.size() - 1)
	_obscured.clear()
	_exposed.clear()
	_shots.clear()
	_socket_count = 0
	_socket_pos = Vector2(SOCKET_HOME_X, SOCKET_HOME_Y)
	_index = 0
	_abort_requested = false
	_summary.visible = false
	_call_label.text = ""
	_power_label.text = ""
	_flash.color = Color(1, 1, 1, 0)
	_clear_floor_icons()

	_traits = _prepare_ammo(traits)

	if _traits.is_empty():
		return await _play_empty()

	visible = true
	_running = true
	get_tree().paused = true
	_input_gate_frame = Engine.get_process_frames() + INPUT_GATE_FRAMES

	_anx_label.text = "ANXIETY %d   (WOBBLE %d/4)" % [_anxiety, _tier]
	_anx_label.add_theme_color_override("font_color", _anxiety_color())
	_set_socket_lit(false)
	_refresh_socket_count()
	if _socket_rect:
		_place(_socket_rect, _socket_pos.x, _socket_pos.y)
	_refresh_queue()

	_hint_label.text = "W / S  AIM     HOLD SPACE  CHARGE     RELEASE  THROW"
	_call_label.text = "HIDE WHAT YOU CAN"
	await _wait(1.1)
	_call_label.text = ""

	# The socket has no capacity limit: land every trait and nothing shows.
	while _index < _traits.size():
		if _abort_requested:
			break
		await _play_one_trait()
		if _abort_requested:
			break
		_index += 1

	# Anything never thrown (aborted) is exposed by default.
	while _index < _traits.size():
		_exposed.append(String(_traits[_index].get("id", "")))
		_index += 1

	_projectile.visible = false
	_set_arrow_visible(false)
	_clear_dots()
	await _show_summary()

	_running = false
	visible = false
	get_tree().paused = false

	var result := {
		"outcome": "cancel" if _abort_requested else "done",
		"obscured": _obscured.duplicate(),
		"exposed": _exposed.duplicate(),
		"shots": _shots.duplicate(),
		"anxiety": _anxiety,
	}
	minigame_finished.emit(result)
	return result


func hide_popup() -> void:
	_running = false
	visible = false
	if get_tree():
		get_tree().paused = false


# ------------------------------------------------------------- ammo setup ----
func _prepare_ammo(traits: Array) -> Array:
	var out: Array = []
	for t in traits:
		if typeof(t) != TYPE_DICTIONARY:
			continue
		var id: String = String(t.get("id", ""))
		if id.is_empty():
			continue
		if int(t.get("amount", 0)) <= 0:
			continue
		out.append({
			"id": id,
			"label": String(t.get("label", id)),
			"amount": int(t.get("amount", 0)),
			"tex": String(t.get("tex", "")),
			"tip": String(t.get("tip", "")),
			"locked": bool(t.get("locked", false)),
		})
	if AMMO_ORDER_WORST_FIRST:
		out.sort_custom(func(a, b): return int(a["amount"]) > int(b["amount"]))
	else:
		out.sort_custom(func(a, b): return int(a["amount"]) < int(b["amount"]))
	return out


func _anxiety_color() -> Color:
	if _anxiety >= 75:
		return C_RED
	if _anxiety >= 45:
		return C_ORANGE
	return C_GREEN


func _play_empty() -> Dictionary:
	visible = true
	_call_label.text = "NOTHING TO HIDE"
	_hint_label.text = "You arrive clean. Enjoy it."
	await _wait(1.8)
	visible = false
	var result := {
		"outcome": "empty", "obscured": [], "exposed": [],
		"shots": [], "anxiety": _anxiety,
	}
	minigame_finished.emit(result)
	return result


# --------------------------------------------------------------- per shot ----
func _play_one_trait() -> void:
	var t: Dictionary = _traits[_index]
	var tex: Texture2D = _load_tex(String(t.get("tex", "")))

	if _card_icon:
		_card_icon.texture = tex
	_card_name.text = String(t.get("label", ""))
	_card_amount.text = "%+d ANXIETY" % int(t.get("amount", 0))
	var proj_icon: TextureRect = _projectile.get_node_or_null("Icon") as TextureRect
	if proj_icon:
		proj_icon.texture = tex
	_projectile.rotation = 0.0
	_projectile.visible = false
	_refresh_queue()

	# New position every throw — no grooving one shot and repeating it.
	_relocate_socket()
	_set_socket_lit(false)

	_angle = ANGLE_START
	_charge = 0.0
	_charge_dir = 1.0
	_wobble_t = randf() * 12.0
	_phase = Phase.AIM
	_power_label.text = "PWR   0%"
	_hint_label.text = "W / S  AIM     HOLD SPACE  CHARGE"

	await _aim_phase()
	if _abort_requested:
		return

	var power: float = await _charge_phase()
	if _abort_requested:
		return

	# The shot leaves at the wobbled angle you were actually sitting on when
	# you let go — not the one you were aiming for.
	var fired_angle: float = _effective_angle()
	var serr := _scaled(RELEASE_SPEED_ERR)
	var speed: float = _speed_for(power) * (1.0 + randf_range(-serr, serr))

	_set_arrow_visible(false)
	_clear_dots()
	_hint_label.text = ""
	_power_label.text = "PWR  %d%%" % int(round(power * 100.0))

	var landing: Dictionary = await _flight_phase(fired_angle, speed)
	await _resolve_landing(t, landing, fired_angle, power)


## Free aim. The wobble runs the whole time and is fully visible on the arrow.
func _aim_phase() -> void:
	var aim_speed := _scaled(AIM_SPEED)
	while _running and not _abort_requested:
		var dt: float = await _tick()
		if _gate_open() and _fire_down():
			_phase = Phase.CHARGE
			return
		var dir := 0.0
		if _up_down():
			dir += 1.0
		if _down_down():
			dir -= 1.0
		_angle = clampf(_angle + dir * aim_speed * dt, ANGLE_MIN, ANGLE_MAX)
		_draw_aim(0.0, false)


## Hold to fill. The meter ping-pongs, so overshooting costs you, and the aim
## keeps wobbling underneath it — two things to read at once, on purpose.
func _charge_phase() -> float:
	var rate := _scaled(CHARGE_RATE)
	_hint_label.text = "RELEASE TO THROW"
	while _running and not _abort_requested:
		var dt: float = await _tick()
		if not _fire_down():
			return clampf(_charge, 0.03, 1.0)
		_charge += _charge_dir * rate * dt
		if _charge >= 1.0:
			_charge = 1.0
			_charge_dir = -1.0
		elif _charge <= 0.0:
			_charge = 0.0
			_charge_dir = 1.0
		_power_label.text = "PWR  %d%%" % int(round(_charge * 100.0))
		_draw_aim(_charge)
	return clampf(_charge, 0.03, 1.0)


func _speed_for(power: float) -> float:
	return lerpf(SPEED_MIN, SPEED_MAX, clampf(power, 0.0, 1.0))


## Aim plus the anxiety wobble. Two out-of-phase sines so it reads as a nervous
## hand rather than a metronome.
func _effective_angle() -> float:
	var amp: float = float(WOBBLE_TIER_DEG[_tier])
	if amp <= 0.001:
		return _angle
	var hz: float = float(WOBBLE_TIER_HZ[_tier])
	var w: float = sin(_wobble_t * TAU * hz) * 0.68 \
		+ sin(_wobble_t * TAU * hz * 2.37 + 1.1) * 0.32
	return clampf(_angle + w * amp, ANGLE_MIN - 8.0, ANGLE_MAX + 8.0)


# --------------------------------------------------------------- physics -----
## Integrate the lob. Holders capture on the way down through their mouth;
## anything else bounces off the woodwork and ends up on the floor.
func _flight_phase(angle_deg: float, speed: float) -> Dictionary:
	_phase = Phase.FLIGHT
	_projectile.visible = true
	var rad := deg_to_rad(angle_deg)
	var pos := Vector2(LAUNCH_X, LAUNCH_Y)
	var vel := Vector2(cos(rad) * speed, -sin(rad) * speed)
	var elapsed := 0.0
	var bounces := 0
	var spin := 0.0
	## Cleared by the first contact with anything. Only a clean pass can stick.
	var clean := true

	while _running and elapsed < FLIGHT_MAX_SEC:
		var dt: float = await _tick()
		elapsed += dt
		var remaining := dt
		while remaining > 0.0:
			var step: float = minf(FLIGHT_STEP, remaining)
			remaining -= step
			var prev := pos
			vel.y += GRAVITY * step
			pos += vel * step

			# --- ceiling: solid, and it kills most of the climb -------------
			if pos.y <= CEILING_Y:
				pos.y = CEILING_Y + 0.5
				vel.y = absf(vel.y) * BOUNCE_CEILING
				vel.x *= 0.85
				bounces += 1
				clean = false

			# --- the socket: stick it, do not carom into it -----------------
			# `clean` goes false on any contact, so a shot that has already
			# bounced cannot score. Without that the right-hand wall sits one
			# icon away from the socket and rebounds everything into it.
			if clean and _capture_hit(pos):
				return {"kind": "socket", "pos": _socket_centre()}

			# --- right wall --------------------------------------------------
			if pos.x > float(BOARD_W) - 3.0:
				pos.x = float(BOARD_W) - 3.0
				vel.x = -absf(vel.x) * BOUNCE_WALL
				bounces += 1
				clean = false

			# --- floor --------------------------------------------------------
			if pos.y >= FLOOR_Y:
				pos.y = FLOOR_Y
				if absf(vel.y) < SETTLE_SPEED and absf(vel.x) < SETTLE_SPEED:
					return {"kind": "floor", "holder": -1, "pos": pos,
						"bounces": bounces}
				vel.y = -absf(vel.y) * BOUNCE_FLOOR
				vel.x *= FRICTION
				bounces += 1
				clean = false

		spin += vel.x * 0.014
		_projectile.rotation = spin * 0.06
		_set_projectile_pos(pos)

	return {"kind": "floor", "holder": -1,
		"pos": Vector2(clampf(pos.x, 6.0, float(BOARD_W) - 6.0), FLOOR_Y),
		"bounces": bounces}


func _resolve_landing(t: Dictionary, landing: Dictionary, fired_angle: float,
		power: float) -> void:
	_phase = Phase.SETTLE
	var id: String = String(t.get("id", ""))
	var kind: String = String(landing.get("kind", "floor"))
	var at: Vector2 = landing.get("pos", Vector2(LAUNCH_X, FLOOR_Y))
	var tex: Texture2D = _load_tex(String(t.get("tex", "")))
	var amount: int = int(t.get("amount", 0))
	var locked: bool = bool(t.get("locked", false))

	if kind == "socket":
		_socket_count += 1
		_obscured.append(id)
		# Snap it dead centre — "mostly fits" on the way in, fills the square
		# perfectly once it is home.
		_set_projectile_pos(at)
		_projectile.rotation = 0.0
		_set_socket_lit(true)
		_refresh_socket_count()
		# Left visible in the recess for the beat, then gone — it is hidden now,
		# and the socket is about to move somewhere else anyway.
		_projectile.visible = true
		_puff_at(at)
		_call_out("OBSCURED", C_GREEN)
		_flash_stage(Color(0.42, 0.85, 0.55, 0.26))
	else:
		_exposed.append(id)
		_projectile.rotation = 0.0
		_projectile.visible = false
		_park_icon(tex, amount, locked,
			Vector2(at.x, FLOOR_Y - float(SLOT_PX) / (SCALE * 2.0)), false)
		_puff_at(at)
		_call_out("ON THE FLOOR", C_RED)
		_flash_stage(Color(0.90, 0.35, 0.30, 0.22))

	_shots.append({
		"id": id,
		"result": "obscured" if kind == "socket" else "exposed",
		"angle": snappedf(fired_angle, 0.1),
		"power": snappedf(power, 0.01),
	})
	_refresh_queue()
	await _wait(0.9)
	_call_label.text = ""
	if kind == "socket":
		_projectile.visible = false
		_set_socket_lit(false)


## Leave a copy of the icon where it ended up, so the board tells the story.
## Same square as the anxiety bar, so the floor reads as a spilled version of
## the bar you have been staring at for two levels.
func _park_icon(tex: Texture2D, amount: int, locked: bool, board_pos: Vector2,
		in_socket: bool) -> void:
	if tex == null:
		return
	var sq := _make_icon_square(tex, amount, locked, C_GOLD if in_socket else null)
	sq.position = Vector2(_px(board_pos.x) - SLOT_PX * 0.5,
		_px(board_pos.y) - SLOT_PX * 0.5)
	if in_socket:
		# Earlier traits shrink back into the recess so the newest reads clearly.
		for old_sq in _floor_icons:
			if is_instance_valid(old_sq) and old_sq.get_meta("in_socket", false):
				old_sq.modulate = Color(1, 1, 1, 0.30)
	sq.set_meta("in_socket", in_socket)
	_stage.add_child(sq)
	_stage.move_child(sq, mini(2, _stage.get_child_count() - 1))
	_floor_icons.append(sq)


func _clear_floor_icons() -> void:
	for r in _floor_icons:
		if is_instance_valid(r):
			r.queue_free()
	_floor_icons.clear()


# ------------------------------------------------------------- presentation --
func _set_projectile_pos(board_pos: Vector2) -> void:
	_projectile.position = Vector2(
		_px(board_pos.x) - float(SLOT_PX) * 0.5,
		_px(board_pos.y) - float(SLOT_PX) * 0.5)


func _set_socket_lit(lit: bool) -> void:
	if _socket_rect == null:
		return
	_socket_rect.texture = _atlas(_tex_socket, 1 if lit else 0,
		SOCKET_CELL_W, SOCKET_CELL_H)


func _refresh_socket_count() -> void:
	if _socket_count_label == null:
		return
	_socket_count_label.text = "HIDDEN %d" % _socket_count if _socket_count > 0 else ""


func _call_out(text: String, color: Color) -> void:
	_call_label.text = text
	_call_label.add_theme_color_override("font_color", color)


func _flash_stage(color: Color) -> void:
	if _flash == null:
		return
	_flash.color = color
	var tw := create_tween()
	tw.set_pause_mode(Tween.TWEEN_PAUSE_PROCESS)
	tw.tween_property(_flash, "color", Color(color.r, color.g, color.b, 0.0), 0.35)


func _puff_at(board_pos: Vector2) -> void:
	if _puff_rect == null:
		return
	_puff_rect.visible = true
	_puff_rect.position = Vector2(
		_px(board_pos.x) - _px(PUFF_CELL) * 0.5,
		_px(board_pos.y) - _px(PUFF_CELL) * 0.5)
	_animate_puff()


## Fire-and-forget so shot resolution is not held up by four frames of dust.
func _animate_puff() -> void:
	for i in range(4):
		if not is_instance_valid(_puff_rect):
			return
		_puff_rect.texture = _atlas(_tex_puff, i, PUFF_CELL, PUFF_CELL)
		await _wait(0.07)
	if is_instance_valid(_puff_rect):
		_puff_rect.visible = false


func _refresh_queue() -> void:
	if _queue_row == null:
		return
	for c in _queue_row.get_children():
		c.queue_free()
	var thrown: int = _obscured.size() + _exposed.size()
	_shots_label.text = "%d / %d" % [thrown, _traits.size()]
	for i in range(_traits.size()):
		var t: Dictionary = _traits[i]
		var border := C_GREY
		if i < thrown:
			border = C_GREEN if _obscured.has(String(t.get("id", ""))) else C_RED
		elif i == _index:
			border = C_GOLD
		var slot := _make_icon_square(_load_tex(String(t.get("tex", ""))),
			int(t.get("amount", 0)), bool(t.get("locked", false)), border)
		slot.modulate = Color(1, 1, 1, 0.45) if i < thrown else Color(1, 1, 1, 1)
		slot.tooltip_text = "%s  %+d" % [String(t.get("label", "")),
			int(t.get("amount", 0))]
		_queue_row.add_child(slot)


# ------------------------------------------------------- aim visualisation ---
func _set_arrow_visible(v: bool) -> void:
	if _arrow_edge:
		_arrow_edge.visible = v
	if _arrow_fill:
		_arrow_fill.visible = v


## The strength arrow: it grows out of the thrower as the meter climbs, and it
## rides the anxiety wobble, so what you see is what will actually leave his
## hand. Drawn as polygons rather than a sprite so the length is continuous.
func _draw_arrow(angle_deg: float, power: float) -> void:
	var rad := deg_to_rad(angle_deg)
	var dir := Vector2(cos(rad), -sin(rad))
	var nrm := Vector2(-dir.y, dir.x)
	var origin := _pxv(Vector2(LAUNCH_X, LAUNCH_Y))
	var body_len := _px(lerpf(ARROW_MIN_LEN, ARROW_MAX_LEN, clampf(power, 0.0, 1.0)))
	var hw := _px(ARROW_SHAFT_HW)
	var head_len := _px(ARROW_HEAD_LEN)
	var head_hw := _px(ARROW_HEAD_HW)
	var tip := origin + dir * (body_len + head_len)
	var neck := origin + dir * body_len

	var pts := PackedVector2Array([
		origin + nrm * hw,
		neck + nrm * hw,
		neck + nrm * head_hw,
		tip,
		neck - nrm * head_hw,
		neck - nrm * hw,
		origin - nrm * hw,
	])
	_arrow_fill.polygon = pts
	_arrow_fill.color = C_GOLD.lerp(C_RED, clampf(power, 0.0, 1.0))

	# Fatten the same shape by 2px for a chunky dark outline.
	var edge := PackedVector2Array()
	var centre := origin + dir * (body_len * 0.5)
	for p in pts:
		edge.append(p + (p - centre).normalized() * 2.0)
	_arrow_edge.polygon = edge
	_set_arrow_visible(true)


## Arrow always; the opening fifth of the arc only once you are charging, when
## there is a real power to trace. Never the whole solution, at any point.
func _draw_aim(power: float, with_trace: bool = true) -> void:
	var ang := _effective_angle()
	_draw_arrow(ang, power)
	if with_trace:
		_draw_trace(ang, _speed_for(power))
	else:
		_clear_dots()


func _clear_dots() -> void:
	for d in _dots:
		(d as TextureRect).visible = false


func _draw_trace(angle_deg: float, speed: float) -> void:
	_clear_dots()
	var rad := deg_to_rad(angle_deg)
	var pos := Vector2(LAUNCH_X, LAUNCH_Y)
	var vel := Vector2(cos(rad) * speed, -sin(rad) * speed)
	var step := 0.012
	# First pass: how long is the whole flight? Only a fraction gets drawn.
	var total := 0
	var p2 := pos
	var v2 := vel
	for _i in range(1200):
		v2.y += GRAVITY * step
		p2 += v2 * step
		total += 1
		if p2.y >= FLOOR_Y or p2.x > float(BOARD_W):
			break
	var show: int = maxi(2, int(total * TRACE_FRACTION))
	var every: int = maxi(1, int(show / float(TRACE_DOTS)))
	var drawn := 0
	for i in range(show):
		vel.y += GRAVITY * step
		pos += vel * step
		if i % every != 0:
			continue
		if drawn >= _dots.size():
			break
		var d: TextureRect = _dots[drawn]
		d.texture = _atlas(_tex_dot, 0 if drawn < 3 else 1, DOT_CELL, DOT_CELL)
		d.position = Vector2(_px(pos.x) - _px(DOT_CELL) * 0.5,
			_px(pos.y) - _px(DOT_CELL) * 0.5)
		d.visible = true
		drawn += 1


# ----------------------------------------------------------------- summary ---
func _show_summary() -> void:
	for c in _summary_rows.get_children():
		c.queue_free()

	var head := Label.new()
	head.text = "WHAT SHE CAN SEE"
	_style_label(head, 14, C_GOLD)
	head.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	_summary_rows.add_child(head)

	_summary_rows.add_child(_summary_group("HIDDEN", _obscured, C_GREEN))
	_summary_rows.add_child(_summary_group("ON THE FLOOR", _exposed, C_RED))

	var foot := Label.new()
	foot.text = "Round 2 draws from what is on the floor."
	_style_label(foot, 8, C_GREY_LT)
	foot.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	_summary_rows.add_child(foot)

	_summary.visible = true
	await _wait(2.6)
	_summary.visible = false


func _summary_group(title: String, ids: Array, color: Color) -> Control:
	var box := VBoxContainer.new()
	box.add_theme_constant_override("separation", 4)
	box.mouse_filter = Control.MOUSE_FILTER_IGNORE

	var lab := Label.new()
	lab.text = "%s  (%d)" % [title, ids.size()]
	_style_label(lab, 9, color)
	box.add_child(lab)

	if ids.is_empty():
		var none := Label.new()
		none.text = "—"
		_style_label(none, 8, C_GREY)
		box.add_child(none)
		return box

	var row := HBoxContainer.new()
	row.add_theme_constant_override("separation", 4)
	row.mouse_filter = Control.MOUSE_FILTER_IGNORE
	box.add_child(row)
	for id in ids:
		var t: Dictionary = _trait_by_id(String(id))
		var slot := _make_icon_square(_load_tex(String(t.get("tex", ""))),
			int(t.get("amount", 1)), false, color)
		slot.tooltip_text = String(t.get("label", id))
		row.add_child(slot)
	return box


func _trait_by_id(id: String) -> Dictionary:
	for t in _traits:
		if String(t.get("id", "")) == id:
			return t
	return {"label": id, "tex": ""}


# ------------------------------------------------------------------ input ----
func _fire_down() -> bool:
	if Input.is_key_pressed(KEY_SPACE):
		return true
	if InputMap.has_action("interact") and Input.is_action_pressed("interact"):
		return true
	return Input.is_key_pressed(KEY_E)


func _up_down() -> bool:
	return Input.is_key_pressed(KEY_W) or Input.is_key_pressed(KEY_UP)


func _down_down() -> bool:
	return Input.is_key_pressed(KEY_S) or Input.is_key_pressed(KEY_DOWN)


func _gate_open() -> bool:
	return Engine.get_process_frames() >= _input_gate_frame


func _input(event: InputEvent) -> void:
	if not visible or not _running:
		return
	if event is InputEventKey and event.pressed and not event.echo:
		if (event as InputEventKey).keycode == KEY_ESCAPE:
			_abort_requested = true
			get_viewport().set_input_as_handled()


# ------------------------------------------------------------------- ticks ---
func _tick() -> float:
	await get_tree().process_frame
	var dt: float = get_process_delta_time()
	_wobble_t += dt
	return minf(dt, 1.0 / 20.0)   # clamp so a hitch cannot teleport the lob


func _wait(sec: float) -> void:
	await get_tree().create_timer(sec, true, false, true).timeout
